

INSERT INTO COACH (CAP, NAME, TOWN) VALUES (true, 'ASH', 'PUEBLO PALETA');
INSERT INTO COACH (CAP, NAME, TOWN) VALUES (false, 'ROGER', 'PUEBLO MOLINA');
INSERT INTO COACH (CAP, NAME, TOWN) VALUES (true, 'PAUL', 'ARRAKIS');

INSERT INTO POKEMON (HEALTH, HEALTH_MAX, LEVEL, COACH_ID, NAME, TYPE) VALUES (100, 200, 22, null, 'SQUIRTLE', 'WATER');
INSERT INTO POKEMON (HEALTH, HEALTH_MAX, LEVEL, COACH_ID, NAME, TYPE) VALUES (200, 400, 26, 1, 'PIKACHU', 'ELECTRIC');
INSERT INTO POKEMON (HEALTH, HEALTH_MAX, LEVEL, COACH_ID, NAME, TYPE) VALUES (300, 400, 25, null, 'BULBASUR', 'GRASS');
INSERT INTO POKEMON (HEALTH, HEALTH_MAX, LEVEL, COACH_ID, NAME, TYPE) VALUES (59, 100, 12, null,'CHARMANDER', 'FIRE');
INSERT INTO POKEMON (HEALTH, HEALTH_MAX, LEVEL, COACH_ID, NAME, TYPE) VALUES (69, 70, 7, 3, 'GENGAR', 'GHOST');