INSERT INTO PLAYER (NAME, COUNTRY, RANKING, ACTIVE) VALUES ('Del potro', 'Argentina', 5, false);
INSERT INTO PLAYER (NAME, COUNTRY, RANKING, ACTIVE) VALUES ('Carlos Alcaraz', 'Spain', 4, true);
INSERT INTO PLAYER (NAME, COUNTRY, RANKING, ACTIVE) VALUES ('Roger Federer', 'Switzerland', 3, false);
INSERT INTO PLAYER (NAME, COUNTRY, RANKING, ACTIVE) VALUES ('Ramón', 'España',1 , true);
INSERT INTO PLAYER (NAME, COUNTRY, RANKING, ACTIVE) VALUES ('Ginés', 'Uruguay', 2, true);

INSERT INTO TOURNAMENT (NAME, PLACE, COURT, PLAYER_ID) VALUES ('Wimbledon', 'England', 'GRASS', null );
INSERT INTO TOURNAMENT (NAME, PLACE, COURT, PLAYER_ID) VALUES ('Roland garros', 'French', 'CLAY', 1 );
INSERT INTO TOURNAMENT (NAME, PLACE, COURT, PLAYER_ID) VALUES ('Usa open', 'USA', 'HARD', null );
INSERT INTO TOURNAMENT (NAME, PLACE, COURT, PLAYER_ID) VALUES ('Australian open', 'Australia', 'HARD', null );
INSERT INTO TOURNAMENT (NAME, PLACE, COURT, PLAYER_ID) VALUES ('Madrid open', 'Madrid', 'CLAY', 2 );